name: Dry Run

on:
  pull_request:
    branches: [ master ]

jobs:
  dry_run:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Dry Run
        uses: sakebook/actions-flutter-pub-publisher@v1.4.1
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          skip_test: true
          dry_run: true
